name: grafica
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pip
  - pyopengl
  - python
  - mesa>=2.3.0
  - trimesh
  - networkx
  - pillow
  - matplotlib
  - scipy
  - cffi
  - shapely
  - rtree
  - click
  - pyvista
  - sympy
  - pip:
    - pyglet>=2.0.0
    - pymunk